### ISSUE TITLE
Failing BigInteger and not-working UnitTests

### ISSUE THREAD

**Issue by onepiecefreak3** [SciresM/CTRAesEngine#1]
Hey there,

I downloaded the whole and didn't change anything in the code. Now I tried to decrypt a .3ds file with DecryptGameNCSD(), which failed.
The code threw an exception at AESEngine.cs Line 812 that the BigInteger for the parameter exponent must not be negative.

I then tried to execute the UnitTests to see if I misunderstood something and if they could help me after executing correct. But all 8 UnitTests failed.

Could you help finding out the problem?

**Comment by SciresM** [comment]
Pushed fix, thanks!

All unit tests pass in my build now.
